# Generated by Django 4.2 on 2023-04-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the site.", max_length=50, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A short name or identifier for the page.",
                        max_length=50,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site that the page name belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_names",
                        to="contents.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ar", "Arabic"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("de", "German"),
                            ("it", "Italian"),
                        ],
                        default="en",
                        help_text="The language of the page.",
                        max_length=2,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the page, up to 200 characters.",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The main content of the page."),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description or summary of the page.",
                        max_length=300,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="A URL for an optional image to display with the page.",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of an optional icon to display with the page.",
                        max_length=50,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the page is currently published and visible to users.",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the page was created.",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the page was last updated.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique URL-friendly identifier for the page. Leave blank to automatically generate from the title."
                    ),
                ),
                (
                    "page_name",
                    models.ForeignKey(
                        help_text="The name of the page.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="contents.pagename",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site that the page belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="contents.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "site", "page_name", "title")},
            },
        ),
    ]
