# Generated by Django 4.2 on 2023-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="page",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="A unique URL-friendly identifier for the page. Leave blank to automatically generate from the title.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagename",
            unique_together={("site", "name")},
        ),
    ]
