# Generated by Django 4.2 on 2023-10-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayOfTheWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Sun", "Sunday"),
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                        ],
                        max_length=3,
                        verbose_name="Day of Week",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Day of the Week",
                "verbose_name_plural": "Days of the Week",
            },
        ),
        migrations.CreateModel(
            name="RateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter a code for the Rate Category.",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a description for the Rate Category.",
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Rate Categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RateCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Rate Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Rate Code Name"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "rate_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratemanagement.ratecategory",
                        verbose_name="Rate Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Code",
                "verbose_name_plural": "Rate Codes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RateOfferProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Rate Offer Product Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Rate Offer Product Name",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Offer Product",
                "verbose_name_plural": "Rate Offer Products",
            },
        ),
        migrations.CreateModel(
            name="RatePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Rate Offer Product Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Rate Offer Product Name",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Pool",
                "verbose_name_plural": "Rate Pools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RateRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter a code for the Rate Restriction.",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a description for the Rate Restriction.",
                        max_length=50,
                    ),
                ),
                (
                    "minimum_stay",
                    models.PositiveIntegerField(default=1, verbose_name="Minimum Stay"),
                ),
                (
                    "maximum_stay",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Maximum Stay"
                    ),
                ),
                (
                    "book_in_advance",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Book in Advance (Days)"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Restriction",
                "verbose_name_plural": "Rate Restrictions",
            },
        ),
        migrations.CreateModel(
            name="RateRuleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("None Defined", "None Defined"),
                            ("Fixed", "Fixed"),
                            ("Percentage Above", "Percentage Above"),
                            ("Percentage Below", "Percentage Below"),
                            ("Amount Above", "Amount Above"),
                            ("Amount Below", "Amount Below"),
                            ("Equal", "Equal"),
                        ],
                        max_length=20,
                        verbose_name="Rate Rule Choice",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Rule Type",
                "verbose_name_plural": "Rate Rule Types",
            },
        ),
        migrations.CreateModel(
            name="RateSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Season Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Season",
                "verbose_name_plural": "Rate Seasons",
            },
        ),
        migrations.CreateModel(
            name="RateSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter a code for the Hotel Category.",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a description for the Hotel Category.",
                        max_length=50,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Enter a display sequence."),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Rate Segments",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="RateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("System Generated", "System Generated"),
                            ("Weekend", "Weekend"),
                            ("Weekday", "Weekday"),
                            ("Seven Day", "Seven Day"),
                        ],
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Type",
                "verbose_name_plural": "Rate Types",
            },
        ),
        migrations.CreateModel(
            name="RateSegmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter a code for the Hotel Category.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a description for the Hotel Category.",
                        max_length=50,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Enter a display sequence."),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.ManyToManyField(
                        related_name="rate_segment", to="ratemanagement.ratesegment"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rate Segment Groups",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="RateOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Offer Name"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "rate_codes",
                    models.ManyToManyField(
                        related_name="offers",
                        to="ratemanagement.ratecode",
                        verbose_name="Rate Codes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Offer",
                "verbose_name_plural": "Rate Offers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RateMirror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "mirrored_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mirrored_rate_mirror",
                        to="ratemanagement.ratecode",
                    ),
                ),
                (
                    "original_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_rate_mirror",
                        to="ratemanagement.ratecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Mirror",
                "verbose_name_plural": "Rate Mirrors",
            },
        ),
        migrations.CreateModel(
            name="RateCodeCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Cluster Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cluster Name"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "rate_codes",
                    models.ManyToManyField(
                        related_name="clusters",
                        to="ratemanagement.ratecode",
                        verbose_name="Rate Codes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Code Cluster",
                "verbose_name_plural": "Rate Code Clusters",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ratecode",
            name="rate_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ratemanagement.ratepool",
                verbose_name="Rate Pool",
            ),
        ),
        migrations.AddField(
            model_name="ratecode",
            name="rate_segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ratemanagement.ratesegment",
                verbose_name="Rate Segment",
            ),
        ),
        migrations.AddField(
            model_name="ratecode",
            name="rate_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ratemanagement.ratetype",
                verbose_name="Rate Type",
            ),
        ),
        migrations.CreateModel(
            name="RateAvailabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Rate Availability Rule Name",
                    ),
                ),
                (
                    "length_of_stay_required",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Length of Stay Required"
                    ),
                ),
                (
                    "advance_booking_required",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Advance Booking Required"
                    ),
                ),
                (
                    "blackout_dates",
                    models.BooleanField(default=False, verbose_name="Blackout Dates"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "days_of_week",
                    models.ManyToManyField(
                        blank=True,
                        related_name="days_of_week",
                        to="ratemanagement.dayoftheweek",
                        verbose_name="Day of the Week",
                    ),
                ),
                (
                    "request_arrival_day",
                    models.ManyToManyField(
                        blank=True,
                        related_name="request_arrival_day",
                        to="ratemanagement.dayoftheweek",
                        verbose_name="Request Arrival Day",
                    ),
                ),
                (
                    "request_stayover_day",
                    models.ManyToManyField(
                        blank=True,
                        related_name="request_stayover_day",
                        to="ratemanagement.dayoftheweek",
                        verbose_name="Request Stayover Day",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Availability Rule",
                "verbose_name_plural": "Rate Availability Rules",
            },
        ),
        migrations.CreateModel(
            name="RateAmounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "rate_gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rate Gross"
                    ),
                ),
                (
                    "rate_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rate Net"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "availability_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratemanagement.rateavailabilityrule",
                        verbose_name="Availability Rule",
                    ),
                ),
                (
                    "mirror_rate_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mirrored_rates",
                        to="ratemanagement.ratecode",
                        verbose_name="Mirror Rate Code",
                    ),
                ),
                (
                    "rate_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ratemanagement.ratecode",
                        verbose_name="Rate Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Amount",
                "verbose_name_plural": "Rate Amounts",
            },
        ),
    ]
