# Generated by Django 4.2 on 2023-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratemanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratepool",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
