# Generated by Django 5.0.1 on 2024-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_remove_categorytranslation_slug_category_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AddField(
            model_name="categorytranslation",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Enter a slug for the content.",
                null=True,
                verbose_name="Slug",
            ),
        ),
    ]
