# Generated by Django 4.2 on 2023-10-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'verbose_name_plural': 'Business Categories'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='job_title',
        ),
        migrations.AddField(
            model_name='testimonialtranslation',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonialtranslation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonialtranslation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
