# Generated by Django 4.2 on 2023-10-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_businesscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialtranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
    ]
