# Generated by Django 4.2 on 2023-10-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_testimonialtranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategorytranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='featuretranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='marketingtranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='offeringtranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
    ]
