# Generated by Django 4.2 on 2023-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_businesscategorytranslation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='site_keywords',
        ),
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='tagline',
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='company_name',
            field=models.CharField(default='sew', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='site_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinformationtranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for the content.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='siteinformationtranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='siteinformationtranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
