# Generated by Django 4.2 on 2023-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_siteinformationtranslation_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
