# Generated by Django 4.2 on 2023-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_siteinformation_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='site_keywords',
            new_name='keywords',
        ),
    ]
