# Generated by Django 4.2 on 2023-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_site_keywords_siteinformation_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategorytranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='featuretranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='marketingtranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offeringtranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='projecttranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicetranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='siteinformationtranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teammembertranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='testimonialtranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='offering',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
