# Generated by Django 4.2 on 2023-10-25 19:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_businesscategorytranslation_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='license_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='register_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='vat_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinformationadditionaltranslation',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter an icon for the content.', max_length=100, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Logo image.', null=True, upload_to=core.models.base_image_path, validators=[core.models.validate_image_extension], verbose_name='Logo Image'),
        ),
    ]
