# Generated by Django 4.2 on 2023-10-27 17:31

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_siteinformation_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Logo image.', null=True, upload_to='home/', validators=[core.models.validate_image_extension], verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_meta_data', to='homepage.siteinformation'),
        ),
    ]
