# Generated by Django 4.2 on 2023-10-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_teammember_whatsapp_url_alter_sitemetadata_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='instagram_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter_url',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='whatsapp_url',
            new_name='whatsapp',
        ),
    ]
