# Generated by Django 4.2 on 2023-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_teammember_github_teammember_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='job_title',
        ),
        migrations.AddField(
            model_name='teammembertranslation',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembertranslation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
