# Generated by Django 4.2 on 2023-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_teammember_bio_remove_teammember_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
