# Generated by Django 4.2 on 2023-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Billing', 'Billing'), ('Main', 'Main')], max_length=255, unique=True, verbose_name='Address Type'),
        ),
    ]
