# Generated by Django 4.2 on 2023-11-23 22:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_addressformat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
    ]
