# Generated by Django 4.2 on 2024-01-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='plotter.body'),
        ),
    ]
