# Generated by Django 4.2 on 2024-01-14 17:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_files_filestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, help_text='Upload an image for the content.', null=True, upload_to=core.models.base_file_path_protected, verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='FilesTranslation',
        ),
    ]
