# Generated by Django 4.2 on 2024-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0004_files_slug_alter_files_file_delete_filestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='part',
            field=models.SlugField(default='', help_text='Enter a part of body.', verbose_name='Part'),
            preserve_default=False,
        ),
    ]
