# Generated by Django 4.2 on 2024-01-19 11:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0005_files_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file for the content.', null=True, upload_to=core.models.base_file_path_protected, verbose_name='File'),
        ),
    ]
