# Generated by Django 4.2 on 2024-01-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0008_remove_files_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body_part_files', to='plotter.bodypart'),
            preserve_default=False,
        ),
    ]
