# Generated by Django 4.2 on 2024-01-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0009_files_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='part',
            new_name='body_part',
        ),
    ]
