# Generated by Django 4.2 on 2024-01-20 09:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0010_rename_part_files_body_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(help_text='Enter the height', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotterMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the content.', null=True, upload_to=core.models.base_image_path, validators=[core.models.validate_image_extension], verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text='Enter an icon for the content.', max_length=100, null=True, verbose_name='Icon')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the content was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time when the content was last modified.', verbose_name='Modified')),
                ('name', models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Body Part',
                'verbose_name_plural': 'Body Parts',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(help_text='Enter the width', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='height',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heights', to='plotter.height'),
        ),
        migrations.AddField(
            model_name='files',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widths', to='plotter.width'),
        ),
    ]
