# Generated by Django 4.2 on 2024-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0011_height_plottermachine_width_files_height_files_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
