# Generated by Django 4.2 on 2024-01-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0012_files_size_alter_files_height_alter_files_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plottermachine',
            options={'verbose_name': 'Plotter Machine', 'verbose_name_plural': 'Plotter Machines'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='application',
        ),
        migrations.AddField(
            model_name='bodypart',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_body_parts', to='plotter.application'),
            preserve_default=False,
        ),
    ]
