# Generated by Django 4.2 on 2024-01-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0013_alter_plottermachine_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarTranslation',
        ),
    ]
