# Generated by Django 4.2 on 2024-01-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0015_cartranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='years',
            field=models.ManyToManyField(blank=True, related_name='cars', to='plotter.year'),
        ),
    ]
