# Generated by Django 4.2 on 2024-01-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0016_remove_car_year_car_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='years',
            new_name='year',
        ),
    ]
